### ISSUE TITLE
Plataforma dos Inventários

### ISSUE THREAD

**Issue by EdSantos754** [marado/RNID#16]
Desde que a competência para os processos de inventários foi passada para os notários, a utilização desta plataforma é obrigatória para quem precisa de recorrer a um processo de inventário. 
(na AR está agora uma proposta que pretende devolver esta competência aos tribunais).

https://www.inventarios.pt/

A plataforma só funciona com alguns browsers desactualizados, alguns dos quais os ficheiros .exe de instalação são fornecidos pela própriaplataforma, pois não é fácil aos utilizadores arranjarem versões antigas de browsers.

A primeira coisa que aparece no site é:

 Aviso:

> Firefox 51 – Windows / Mac
> Outros navegadores p/XP, VISTA - SLIMJET v. 10.0.11
> Outros navegadores p/WIN7 – Maxthon 4.9 ou SLIMJET v. 10.0.11
> Outros navegadores p/Win10 - INTERNET EXPLORER, Maxthon 4.9 ou SLIMJET v. 10.0.11 

Não há opções para Linux.

**Comment by marado** [comment]
infelizmente, estando este site fora das mãos da AP, o RNID não se lhe aplica.
