### ISSUE TITLE
Citius - Verificação difícil

### ISSUE THREAD

**Issue by hugopeixoto** [marado/RNID#55]
O script de verificação do Citius funciona vendo se o documento https://citius.tribunaisnet.mj.pt/habilus/Docs/CITIUS_WEB_FIREFOX_MARCO_2017.pdf ainda existe.

Dado o nome (FIREFOX_MARCO_2017), não sei se alguma vez vai ser apagado. Potencialmente lançariam um documento novo (AGOSTO_2020) a indicar que já não precisam de java, ou assim.

Não duvido que o incumprimento ainda se mantenha, mas talvez seja preciso verificação manual por parte de alguém com credenciais de acesso.

Acham que a existência do script pode levar a falsa sensação de confiança, e que estejamos a marcar o incumprimento cegamente?

**Comment by marado** [comment]
É possível, mas não estou a ver forma mais viável de fazer isto, não sendo
advogado/tendo credenciais.

Estou disponível para ser convencido que vale mais não ter script do que
ter este que pode falhar ;-)

**Comment by hugopeixoto** [comment]
Não sendo eu advogado, também, é difícil dizer. Nem percebo bem para que serve esta applet.

Entretanto, fui ler/escavar um bocado sobre isto. Segundo o pdf do script:
> para  efeitos  de  entrega e assinatura eletrónica de peças  processuais

Segundo (Esta notícia de 2019-09)[https://portal.oa.pt/comunicacao/noticias/2019/07-e-08/nota-informativa-do-igfej/]:

> No sistema CITIUS passará a ser também utilizado o SIGNIUS para suporte à assinatura digital, sendo que, também a partir de 11 de setembro se verificarão mudanças no modo de preparação e entrega de peças processuais, nomeadamente a submissão individualizada dos documentos que a compõe.

Segundo [o PDF na notícia](https://portal.oa.pt/media/128363/citius_set_2019_signius.pdf):

> Neste contexto, o sistema atual de assinatura de peças processuais por recurso à **JAVA APPLET**, será **DESCONTINUADO** a  partir  de  11  de  setembro,  dando  lugar  a  um  novo  sistema  de  assinatura,designado por **SIGNIUS**,  o qual,aliás,se encontra  em utilização desde maio  de 2018 no SITAF –Mandatários.Com a dispensa da necessidade de utilização da java applet, passa a ser possível, com maior segurança, a utilização doCITIUS através dos vários navegadores atualmente suportados pelos principais fabricantes.

Parece que a java applet já não se usa, e agora é suposto usar a aplicação SIGNIUS?

**Comment by hugopeixoto** [comment]
Tal como o autenticacao.gov, o motivo principal parece ser conseguir integrar com smartcards.

Enquanto no caso do autenticacao.gov talvez se pudesse usar WebAuthn para autenticação, aqui não sei se o mesmo é possível. Não conheco webauthn o suficiente para saber se é possível assinar documentos, ou se há algum outro standard para isso.
