### ISSUE TITLE
RTP - Incumprimento corrigido mas documentação deixada para trás?

### ISSUE THREAD

**Issue by hugopeixoto** [marado/RNID#56]
Não encontro nenhum conteúdo Flash nem WMV no site da RTP.

É possível que os links descritos na tabela são apenas artefactos antigos? Os links não aparecem no menu em "Utilização", secção em qual supostamente se encontram. Outra página que também está debaixo desta categoria e escondida é esta: https://media.rtp.pt/empresa/utilizacao/browser/

>  Após consultarmos os mais variados sites e publicações, verificámos que mais de 90% dos computadores que acedem à Internet usam o Browser “Internet Explorer”, da Microsoft. Para poder visualizar correctamente o site da RTP sem prejuízo no design das páginas, deve ter instalado o Internet Explorer 5.0 ou superior. 

que parece.. um bocadinho deactualizada.

Encontrei também uma notícia de 2015:

[RTP deixa de suportar conteúdos Windows Media Áudio](https://media.rtp.pt/empresa/wp-content/uploads/sites/31/2016/11/RTP-deixa-de-suportar-conteudos-windows-media-audio.pdf)

Edit: pode haver ainda conteúdos em flash ou wmv. Se alguém souber de algum link mais directo, podiamos usar isso como garantia / check.

**Comment by hugopeixoto** [comment]
Usei o formulário de contacto a perguntar. Não sei se vou ter resposta, não recebi confirmação de envio no email.

**Comment by marado** [comment]
Não conheço nenhum link directo, mas não foste o primeiro a contactá-los a perguntar isso, sem resposta...

**Comment by marado** [comment]
Visto que eles agora até têm DRM nas RTP1 e RTP2 (https://github.com/marmelo/streaming-pt/issues/62#issuecomment-893388986), a RTP está certamente a não cumprir (ainda que a parte da documentação e isso já não esteja actual em relação aos incumprimentos).

**Comment by marado** [comment]
Já deixaram de usar DRM.

**Comment by hugopeixoto** [comment]
Queremos manter o incumprimento apesar de ser apenas uma referência obsoleta num FAQ? Não vejo indícios de incumprimento "a sério".

**Comment by marado** [comment]
Já voltaram a meter DRM... https://twitter.com/mind_booster/status/1562592932477435905

**Comment by marado** [comment]
Vou fechar este issue: já não temos problemas nenhuns com WMV ou documentação obsoleta.
A questão do DRM passa a ter um issue próprio: #99 .
