### ISSUE TITLE
Access Monitor - Falta de HTTPS com formulário de autenticação

### ISSUE THREAD

**Issue by hugopeixoto** [marado/RNID#57]
http://accessmonitor.acessibilidade.gov.pt/ams/

**Comment by hugopeixoto** [comment]
Enviei email para ama@ama.pt a reportar.

**Comment by marado** [comment]
:+1: , queres fazer um PR com a adição disto no README? Pontos extra se vier também com um script! ;-)

**Comment by hugopeixoto** [comment]
Sim, farei o PR em breve. Desculpa o spam de issues, mas estava a ir um a um e fui reportando o que encontrava para não me esquecer, PRs no fim.

**Comment by marado** [comment]
Nada de pedir desculpas por contribuir, venham mais issues e PRs! ;-)

**Comment by hugopeixoto** [comment]
@marado : recebi resposta, dizem que o site foi descontinuado e que sairá versão nova em breve. Qual o processo aqui? mantém-se o incumprimento até surgir substituto?

**Comment by marado** [comment]
O incumprimento existe até que hava o novo site, mas essa informação deve ser indicada na tabela, numa nota de rodapé (como a que já lá está, para o canal parlamento).

A reabrir o issue.
