### ISSUE TITLE
Automatizar testes de acessibilidade

### ISSUE THREAD

**Issue by hugopeixoto** [marado/RNID#66]
Muitos dos scripts verificam a WCAG2.x compliance através de proxy checks, por não haver nenhuma ferramenta fácil de usar para fazer a análise completa.

Ficam aqui algumas sugestões de ferramentas:

- https://github.com/dequelabs/axe-cli
- https://developers.google.com/web/tools/lighthouse/#cli

**Comment by marado** [comment]
A ideia é boa na generalidade, complicada no especíico. Não encontrei nenhuma ferramenta que tenha gostado, e essas duas também não me convencem:

O `axe-cli` é fickle na forma como tem de ser executado (por ex., nalguns cenários tens de lhe apontar especificamente a path para o chromedriver, para funcionar, o que significa que tinhamos de ter essa path hardcoded...), o `lighthouse' parece não ser muito bom para automatismos (isto é, para ser executado e o seu resultado parsado automaticamente num script). 

Dito isto, se tiveres vontade de investigar e fazer um PR a tentar usar uma destas ferramentas (ou outras do género), cá estarei para testar, prove me wrong! :-)

**Comment by marado** [comment]
Se fizermos o #68 já não precisamos disto.

**Comment by marado** [comment]
Resolvido com o #68 .
