### ISSUE TITLE
SNS

### ISSUE THREAD

**Issue by marado** [marado/RNID#67]
https://www.sns.gov.pt/sns/pesquisa-prestadores/ - a pesquisa não funciona em Firefox, validar se é um incumprimento

**Comment by hugopeixoto** [comment]
A pesquisa parece-me funcionar no meu firefox, tirando o google maps que às vezes vai pro meio do mar. Se não preencheres nenhum campo demora um bocado (fica a puxar os dados todos), será disso? Que comportamento estás a ter?

**Comment by marado** [comment]
Já funciona aqui também, pode ter sido um "soluço". Obrigado por testares!
