### ISSUE TITLE
"delegar" incumprimentos de acessibilidade

### ISSUE THREAD

**Issue by marado** [marado/RNID#68]
Visto que há o observatório https://observatorio.acessibilidade.gov.pt/ , valerá a pena manter esta lista sem a parte de acessibilidade?

Ou, talvez, ter uma lista diferente dedicada à acessibilidade só para casos em que foi pedida a resolução (visto que o observatório, pelo que me parece, não alerta os sites dos seus erros)?

**Comment by hugopeixoto** [comment]
Como o esforço para verificar e manter os checks de acessibilidade é significativamente mais alto que o resto, a ideia parece-me tentadora. Talvez substituir por um link para o observatório?

**Comment by marado** [comment]
A ideia de ter um link para lá (com algum texto explanatório) parece-me a melhor opção.
@hugopeixoto se quiseres fazer um pull request estás à vontade... ;-)

**Comment by hugopeixoto** [comment]
> A ideia de ter um link para lá (com algum texto explanatório) parece-me a melhor opção.
> @hugopeixoto se quiseres fazer um pull request estás à vontade... ;-)

Já não pego nisto há algum tempo, agora ao reler fiquei com dúvidas se percebi bem.

Dizes remover todos os checks de acessibilidade do repositório e meter um link genérico para o observatório com uma explicação de que não vamos manter essa monitorização aqui?

**Comment by marado** [comment]
Não tenho bem a certeza qual será a melhor aproximação, estou aberto a ideias, comentários e sugestões.

**Comment by hugopeixoto** [comment]
OK, então sugiro fazermos o que disse. Na conversão que estou a fazer no #71 estou já a omitir as entradas relacionadas com acessibilidade. Depois faltará acrescentar o texto a apontar para o observatório e explicar a decisão.

**Comment by marado** [comment]
Acho que podemos fazer esta limpeza primeiro, e isso depois simplifica o #71 .

**Comment by hugopeixoto** [comment]
> Acho que podemos fazer esta limpeza primeiro, e isso depois simplifica o #71 .

Segui a tua sugestão e fiz o PR #88.

**Comment by marado** [comment]
Resolvido, obrigado @hugopeixoto !
