### ISSUE TITLE
https://www.app.gov.pt/ - HTTPS

### ISSUE THREAD

**Issue by marado** [marado/RNID#75]
https://www.app.gov.pt/ tem certificado HTTPS com problemas (é daqueles da Multicert que têm de ser trocados)

**Comment by hugopeixoto** [comment]
Mandei email para ama@ama.pt a chatear, aguardo resposta.

**Comment by hugopeixoto** [comment]
Parece-me já estar resolvido. Confirmas?

**Comment by marado** [comment]
Bem visto, obrigado!
