### ISSUE TITLE
Incumprimento CML resolvido?

### ISSUE THREAD

**Issue by hugopeixoto** [marado/RNID#79]
Apesar do script automático continuar a encontrar o PDF, o site em si parece já não o utilizar.

Não percebo bem, mas parece-me que agora as ocorrências são submetidas via "Loja Lisboa Online".
Não sendo lisboeta, não queria estar a registar-me nesse site para perceber se ainda há incumprimento ou não.

Alguém pode verificar? A ideia é perceber se a "participação de ocorrências" funciona através do download de um PDF com formulários embutidos (XFA).

Passos para descobrir isto:
- Aceder a https://informacoeseservicos.lisboa.pt/servicos/detalhe/participacao-de-ocorrencia-em-espaco-publico-e-pedido-de-indemnizacao
- Carregar em "Submeter online"
- Fazer login
- Explorar o processo de participar uma ocorrência

Se for tudo com formulários web:
- a ocorrência há de estar resolvida
Se precisar de download de um PDF:
- anexar a este issue o link do PDF para podermos investigar se continua a usar tecnologias XFA

**Comment by marado** [comment]
Algures nesse formulário web é-nos dito "Descarregue o [formulário ](https://informacoeseservicos.lisboa.pt/fileadmin/informacoes_servicos/pedidos/_transversais/CML_participacao_ocorrencia.pdf)e anexe-o depois de preenchido e assinado."
O ficheiro não aparenta estar por detrás de autenticação.
