### ISSUE TITLE
Como verificar o incumprimento Facturas / Flash?

### ISSUE THREAD

**Issue by hugopeixoto** [marado/RNID#80]
Na secção de incumprimentos das finanças existe uma entrada "exportação de facturas precisa de flash".

Como posso validar o incumprimento? Qual a página que precisa de flash?

Não temos automatismo e o link aponta directamente para o ficheiro flash, que pode já não estar a ser usado.

**Comment by marado** [comment]
Verificou-se manualmente que este incumprimento já se encontra resolvido.
