### ISSUE TITLE
incumprimento RNID em todo site https://apps.dgeg.gov.pt/

### ISSUE THREAD

**Issue by anatolwa** [marado/RNID#95]
toda documentação está ou em *.xlsx ou *.docx sem nenhuma alternativa a vista

**Comment by marado** [comment]
O novo `apps.dgeg.gov.pt` já não aparenta ter documentação ou incumprimentos, e há um incumprimento no site principal da dgeg, para o qual foi acrescentado um incumprimento na tabela, https://github.com/marado/RNID/blob/master/README.md?plain=1#L39 . Vou dar este issue como encerrado, mas se por acaso me estiver a escapar alguma coisa, por favor avisa!
